apiVersion: apps/v1
kind: Deployment
metadata:
  name: glen-api-gateway
  namespace: glen-system
  labels:
    app: glen-api-gateway
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: glen-api-gateway
  template:
    metadata:
      labels:
        app: glen-api-gateway
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: api-gateway
        image: dqx0/glen-api-gateway:v1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: API_GATEWAY_PORT
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: AUTH_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: USER_SERVICE_URL
        - name: SOCIAL_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: SOCIAL_SERVICE_URL
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: LOG_LEVEL
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: glen-api-gateway-service
  namespace: glen-system
  labels:
    app: glen-api-gateway
  annotations:
    cloud.google.com/backend-config: '{"default": "glen-api-gateway-config"}'
spec:
  selector:
    app: glen-api-gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: glen-api-gateway-config
  namespace: glen-system
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 8080
    type: HTTP
    requestPath: /health