apiVersion: apps/v1
kind: Deployment
metadata:
  name: glen-auth-service
  namespace: glen-system
  labels:
    app: glen-auth-service
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: glen-auth-service
  template:
    metadata:
      labels:
        app: glen-auth-service
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: auth-service
        image: dqx0/glen-auth-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: ENVIRONMENT
          value: production
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: AUTH_SERVICE_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: DB_PASSWORD
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_SSLMODE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: REDIS_PORT
        - name: REDIS_ADDR
          value: "$(REDIS_HOST):$(REDIS_PORT)"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: JWT_SECRET
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: OAUTH_CLIENT_ID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: OAUTH_CLIENT_SECRET
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: LOG_LEVEL
        # WebAuthn Configuration
        - name: WEBAUTHN_RP_DISPLAY_NAME
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: WEBAUTHN_RP_DISPLAY_NAME
        - name: WEBAUTHN_RP_ID
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: WEBAUTHN_RP_ID
        - name: WEBAUTHN_RP_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: WEBAUTHN_RP_ORIGINS
        - name: WEBAUTHN_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: WEBAUTHN_TIMEOUT
        - name: WEBAUTHN_DEBUG
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: WEBAUTHN_DEBUG
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: glen-auth-service
  namespace: glen-system
  labels:
    app: glen-auth-service
spec:
  selector:
    app: glen-auth-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP