apiVersion: v1
kind: ConfigMap
metadata:
  name: glen-config
  namespace: glen-system
data:
  # Database Configuration
  DB_HOST: "104.198.122.76"  # Cloud SQL パブリック IP
  DB_PORT: "5432"
  DB_NAME: "glen_prod"
  DB_USER: "glen_user"
  DB_SSLMODE: "require"
  
  # Redis Configuration
  REDIS_HOST: "10.230.40.112"  # Redis IP (ダイレクト ピアリング)
  REDIS_PORT: "6379"
  
  # Service Configuration
  AUTH_SERVICE_PORT: "8081"
  USER_SERVICE_PORT: "8082"
  SOCIAL_SERVICE_PORT: "8083"
  API_GATEWAY_PORT: "8080"
  
  # URLs
  AUTH_SERVICE_URL: "http://glen-auth-service:8081"
  USER_SERVICE_URL: "http://glen-user-service:8082"
  SOCIAL_SERVICE_URL: "http://glen-social-service:8083"
  
  # Frontend Configuration
  VITE_API_URL: "https://api.glen.dqx0.com"
  
  # Environment
  ENV: "production"
  LOG_LEVEL: "INFO"