apiVersion: apps/v1
kind: Deployment
metadata:
  name: glen-frontend
  namespace: glen-system
  labels:
    app: glen-frontend
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: glen-frontend
  template:
    metadata:
      labels:
        app: glen-frontend
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: dqx0/glen-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: VITE_API_URL
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: glen-frontend-service
  namespace: glen-system
  labels:
    app: glen-frontend
spec:
  selector:
    app: glen-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer