apiVersion: apps/v1
kind: Deployment
metadata:
  name: glen-social-service
  namespace: glen-system
  labels:
    app: glen-social-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glen-social-service
  template:
    metadata:
      labels:
        app: glen-social-service
        version: v1
    spec:
      containers:
      - name: social-service
        image: DOCKER_HUB_USERNAME/glen-social-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: SOCIAL_SERVICE_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: DB_PASSWORD
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: DB_SSLMODE
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: REDIS_PORT
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: GITHUB_CLIENT_SECRET
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: DISCORD_CLIENT_ID
        - name: DISCORD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: glen-secrets
              key: DISCORD_CLIENT_SECRET
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: glen-config
              key: LOG_LEVEL
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: glen-social-service
  namespace: glen-system
  labels:
    app: glen-social-service
spec:
  selector:
    app: glen-social-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP